---
all:
  hosts:
    alvertsworks-01:
      hostname: alvertsworks-01
      IPv4: 192.168.50.2
      ansible_host: 192.168.50.2
      ansible_port: 2222
      ansible_ssh_user: "vagrant"
      ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"