---
all:
  hosts:
    alvertsworks01:
      hostname: alvertsworks01
      ansible_host: 100.167.0.213
      ansible_port: 22
      ansible_ssh_user: "vagrant"
      ansible_ssh_private_key_file: "keys/private_key"
