---
- name: Main
  hosts: alvertsworks01
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed.
      ansible.builtin.apt:
        upgrade: false
        update_cache: true
        cache_valid_time: 86400 # one day

  tasks:
    - name: Health check.
      ansible.builtin.command: echo "OK"
      register: response
      changed_when: response.rc != 0
